
# Use the official PHP 8.2 Apache base image
FROM php:8.2-apache

# Install MySQL client
RUN apt-get update && apt-get install -y default-mysql-client
# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Set up Laravel Artisan 
COPY . /var/www
WORKDIR /var/www
RUN composer install

# Configure Apache
COPY apache-config.conf /etc/apache2/sites-available/000-default.conf
RUN a2enmod rewrite

# Expose port 80
EXPOSE 80

# Start Apache
CMD ["apache2-foreground"]